### ISSUE TITLE
'Describe' step exposes nothing actionable

### ISSUE THREAD

**Issue by ghost** [samuelguebo/thenoun-uploader#2]
see screenshot:
![image](https://user-images.githubusercontent.com/634501/88444024-4ad00c00-cdd8-11ea-85ed-aa256a2a58f0.png)

**Comment by samuelguebo** [comment]
Thanks for flagging it @ArloJamesBarnes 
Can I see the icon you have imported?

@ArloJamesBarnes, as github doesn't support svg, you can share it with me using https://gofile.io/uploadFiles
Here's a icon I'm testing with: https://gofile.io/d/uwfXCq

**Comment by ghost** [comment]
sorry for the delay in response, my connection was down
```svg
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd">
<svg version="1.0" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 72.613 125" enable-background="new 0 0 72.613 100" xml:space="preserve">
<circle cx="23.177" cy="18.7" r="4.173"/>
<circle cx="49.436" cy="18.7" r="4.173"/>
<path d="M0,0v39.225h31.896v3.34L0,42.567V100h18.544l14.114-14.114l-8.111-8.11l8.111-8.111l-2.371-2.37l-10.48,10.481l4.598,4.599
	l-9.279,9.28H8.346V50.912h55.921v40.742h-6.778l-9.28-9.28l4.599-4.599L42.325,67.294l-2.371,2.37l8.112,8.111l-8.112,8.11
	L54.069,100h18.544V42.567l-31.896-0.001v-3.34h31.896V0H0z M64.267,30.879H8.346V7.75h55.921V30.879z"/>
<rect x="31.486" y="72.954" transform="matrix(0.7071 -0.7071 0.7071 0.7071 -44.3617 48.4522)" width="9.641" height="9.642"/>
<text x="0" y="115" fill="#000000" font-size="5px" font-weight="bold" font-family="'Helvetica Neue', Helvetica, Arial-Unicode, Arial, Sans-serif">
Created by Edward Boatman
</text>
<text x="0" y="120" fill="#000000" font-size="5px" font-weight="bold" font-family="'Helvetica Neue', Helvetica, Arial-Unicode, Arial, Sans-serif">
from the Noun Project
</text>
</svg>
```

**Comment by samuelguebo** [comment]
@ArloJamesBarnes, the code for the SVG works you shared works fine. I think you should double check the filename. The uploader extracts metadata from the filename (title and icon ID). When downloaded from thenoun, the SVG files have names like `noun_happy earth day_25859052.svg`

Could you indicate the filename of the icon you tried to upload?

**Comment by ghost** [comment]
The default name from https://thenounproject.com/edward/uploads/?i=699, `noun_Robot_699.svg`.

**Comment by samuelguebo** [comment]
Many thanks @ArloJamesBarnes, it was helpful. I submitted a patch (64833724f1185d75feee496e5b15594062f050cf) and it should fix it. Please clear the cache before trying again.

**Comment by ghost** [comment]
The patch seems to have fixed that problem; after shift-reloading to clear the cache, I am able to see the description step. However (and perhaps this should be a new issue) changing the name doesn't change the name listed in summary at the final step, and it seemed not to upload anyway.

edit: when trying to see if it would work if I didn't change the name (same file), I shift-reloaded again and the missing description step returned :/

**Comment by samuelguebo** [comment]
@ArloJamesBarnes, thanks for spending time on this. Could you indicate the icon url on the nounproject, so I can try to reproduce the error on my end with the same file. Also, please do me a favor and share with me the errors you may find in your [browser console](https://balsamiq.com/support/faqs/browserconsole/).

Thank you.
Edit: It may be helpful to tell me the browser you are using. You may also try a different browser.

**Comment by ghost** [comment]
URL is the same as [before](#issuecomment-664738396), I'll keep trying for that one unless you think something specific to the file or filename is causing the problem.
![image](https://user-images.githubusercontent.com/634501/88968023-e5fb3280-d26b-11ea-93f5-1a69202d308b.png)
![image](https://user-images.githubusercontent.com/634501/88968060-f4e1e500-d26b-11ea-9ab7-520083aca4b7.png)
![image](https://user-images.githubusercontent.com/634501/88968111-0c20d280-d26c-11ea-9d44-ae260a9ba080.png)
despite this, nothing appears in my uploads or at either filename.
console errors didn't seem to pertain:
![image](https://user-images.githubusercontent.com/634501/88968931-53f42980-d26d-11ea-8cdd-5bb690ef10ff.png)
![image](https://user-images.githubusercontent.com/634501/88969038-771ed900-d26d-11ea-8e96-73f22fc18cd3.png)
about:support says:
Name 	Firefox
Version 	78.0.2
Build ID 	20200708170202
Tried on Debian and Win7 to the same results.
Chrome seems just to load endlessly after returning from OAuth.

**Comment by samuelguebo** [comment]
Hey @ArloJamesBarnes, the simulated upload worked fine as per https://commons.wikimedia.org/w/index.php?title=User:African_Hope/TheNounProject&action=history

For the tests, when the upload is successful, the SVG file isn't directly available on Commons. Instead the content (template, description, etc) is inserted in a sandbox: https://commons.wikimedia.org/wiki/User:African_Hope/TheNounProject. Once we're comfortable with the metadata, I can adjust the workflow to actually import the icons to Commons. I did not want to flood Commons with test files.

Update:
I'd suggest we run a few more test. I'll add the renaming feature as it wasn't implemented yet. For now, if you have objections I'd close this ticket and you can create another one related to the renaming or anything else you may come across.

**Comment by ghost** [comment]
I see then, closing.

(BTW, I made a category:vector icons by Edward Boatman [currently including derivs too but I plan to split that off soon], perhaps the tool could be configured to link such cats to a NP user?)

**Comment by samuelguebo** [comment]
Hey @ArloJamesBarnes,
I like the idea of letting the user specify one or more categories where the icon could go. I think it’s an interesting feature. You can create an issue an flag it as a feature so that I don’t forget.

Many thanks again for your time and inputs during these tests.
